employee_management/employee/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import glowna
from . import views


app_name = 'employee'
urlpatterns = [
    path('', glowna, name='start'),
    path('register/', views.register_request, name='register'),
    path('login/', views.login_request, name='login_request'),
    path('logout/', views.logout_request, name='logout_request'),
    path('add-employee/', views.AddEmployee.as_view(), name='add_employee'),
    path('list_employee/', views.EmployeeView.as_view(), name='list_employee'),
    path('update_employee/<int:pk>/update/', views.EmployeeUpdate.as_view(), name='update_employee'),
    path('delete_employee/<int:pk>/delete/', views.EmployeeDelete.as_view(), name='delete_employee'),

    path('dept_create/', views.DeptCreate.as_view(), name='dept_create'),
    path('dept/<int:pk>/update/', views.DeptUpdate.as_view(), name='dept_update'),
    path('dept/<int:pk>/delete/', views.DeptDelete.as_view(), name='dept_delete'),
    path('dept_list', views.DeptView.as_view(), name='dept_list'),
]

employee_management/employee_management/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('employee.urls')),
]

employee_management/employee/models.py
from django.db import models
from datetime import date
from .choices import Supervisors, Departments


# Create your models here.

class Department(models.Model):
    name = models.CharField(max_length=255, unique=True)
    ''' foreigner key Employee '''



dept_list = []
emp = Department.objects.all()
for count,i in enumerate(emp,start=0):
    dept_list.append((count, i.name))

class Employee(models.Model):
    ''' '''

    usercode = models.IntegerField(unique=True)
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    team_leader = models.BooleanField(default=False)
    supervisor = models.PositiveSmallIntegerField(choices=Supervisors.SUPERVISORS, default=0)
    shift = models.PositiveSmallIntegerField(default=None, null=True)
    start_work = models.DateField(default=date.today)
    dept = models.CharField(max_length=255)

    def __str__(self):
        return f"{self.usercode} - {self.first_name} {self.last_name}"



class Operations(models.Model):
    ''' foreigner key Employee '''
    name = models.CharField(max_length=255, unique=True)
    dept = models.ForeignKey(Department, on_delete=models.CASCADE)
    skills = models.ForeignKey(Employee, on_delete=models.SET_NULL, blank=True, null=True)

class Supervisors():
    BRAK, FIRST, SECOND = 0,1,2


    SUPERVISORS =  (
        (BRAK, 'brak'),
        (FIRST, 'Tomasz'),
        (SECOND, 'Iwona')
    )

employee_management/employee/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms import ModelForm
from .models  import Employee

class NewUserForm(UserCreationForm):
    email = forms.EmailField(required=False)

    class Meta:
        model = User
        fields = ('username', 'password1', 'password2')

    def save(self, commit=True):
        user = super(NewUserForm, self).save(commit=False)
        if commit:
            user.save()
        return user


class AddEmployeeForm(ModelForm):
    class Meta:
        model = Employee
        fields = [
            'usercode',
            'first_name',
            'last_name',
            'team_leader',
            'supervisor',
            'shift',
            'start_work',
            'dept',
        ]

employee_management/employee/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib import messages
from django.urls import reverse_lazy
from django.views import View
from .models import Employee, Department, Operations
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .forms import NewUserForm, AddEmployeeForm



def glowna(request):
    employee = Employee.objects.all()
    ctx = {'employee': employee}
    return render(request,'main_side.html', ctx)

def register_request(request):

    if request.method == "POST":
        form = NewUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(request, "Registration successful." )
            return render(request, "main_side.html")
        messages.error(request, "Unsuccessful registration. Invalid information.")
    form = NewUserForm()
    return render(request=request, template_name="register.html", context={"register_form":form})

def login_request(request):

    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.info(request, f"You are now logged in as {username}.")
                return redirect('/')
            else:
                messages.error(request,"Invalid username or password.")
        else:
            messages.error(request,"Invalid username or password.")
    form = AuthenticationForm()
    return render(request=request, template_name="login.html", context={"login_form":form})

def logout_request(request):

    logout(request)
    messages.info(request, "You have successfully logged out.")
    return redirect('/')

# ----------------  CRUD Employee------------------------------------

class AddEmployee(LoginRequiredMixin, View):
    template = 'add_employee.html'
    success_url = reverse_lazy('employee:start')

    def get(self, request):
        form = AddEmployeeForm()
        ctx = {'form': form}
        return render(request, self.template, ctx)

    def post(self, request):
        form = AddEmployeeForm(request.POST)
        if not form.is_valid():
            ctx = {'form': form}
            return render(request, self.template, ctx)

        form.save()
        return redirect(self.success_url)

class EmployeeView(LoginRequiredMixin, View):
    template = 'employee_list.html'

    def get(self, request):
        employee = Employee.objects.all()
        print(employee)
        ctx = {'employee': employee}
        return render(request, self.template, ctx)

class EmployeeUpdate(LoginRequiredMixin, View):
    model = Employee
    success_url = reverse_lazy('employee:start')
    template = 'add_employee.html'

    def get(self, request, pk):
        employee = get_object_or_404(self.model, pk=pk)
        form = AddEmployeeForm(instance=employee)
        ctx = {'form': form}
        return render(request, self.template, ctx)

    def post(self, request, pk):
        employee = get_object_or_404(self.model, pk=pk)
        form = AddEmployeeForm(request.POST, instance=employee)
        if not form.is_valid():
            ctx = {'form': form}
            return render(request, self.template, ctx)

        form.save()
        return redirect(self.success_url)

class EmployeeDelete(LoginRequiredMixin, View):
    model = Employee
    success_url = reverse_lazy('employee:start')
    template = 'employee_confirm_delete.html'

    def get(self, request, pk):
        employee = get_object_or_404(self.model, pk=pk)
        form = AddEmployeeForm(instance=employee)
        ctx = {'employee': employee}
        return render(request, self.template, ctx)

    def post(self, request, pk):
        employee = get_object_or_404(self.model, pk=pk)
        employee.delete()
        return redirect(self.success_url)

# ---------- CRUD Department

class DeptView(LoginRequiredMixin, View):
    template = 'department_list.html'

    def get(self, request):
        departments = Department.objects.all()
        ctx = {'departments': departments}
        return render(request, self.template, ctx)

class DeptCreate(LoginRequiredMixin, CreateView):
    model = Department
    fields = '__all__'
    success_url = reverse_lazy('employee:start')


class DeptUpdate(LoginRequiredMixin, UpdateView):
    model = Department
    fields = '__all__'
    success_url = reverse_lazy('employee:start')


class DeptDelete(LoginRequiredMixin, DeleteView):
    model = Department
    fields = '__all__'
    success_url = reverse_lazy('employee:start')
    template = 'department_confirm_delete.html'


    def get(self, request, pk):
        department = get_object_or_404(self.model, pk=pk)
        form = AddEmployeeForm(instance=department)
        ctx = {'department': department}
        return render(request, self.template, ctx)

employee_management/employee/templates/CRUD_template/add_employee.html
{% extends 'base.html'%}
{% load static %}
{% block title %}główna{% endblock %}

{% block content %}
<p>Dodawanie pracownika</p>
      <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
    <input type="submit" onclick="window.location='/' ; return false;" value="Cancel">
  </form>
{% endblock %}

employee_management/employee/templates/CRUD_template/dept_confirm_delete.html
{% extends 'base.html'%}
{% load static %}
{% block title %}główna{% endblock %}

{% block content %}

{% endblock %}

employee_management/employee/templates/CRUD_template/employee/department_confirm_delete.html
{% extends 'base.html' %}
{% load static %}
{% block title %}główna{% endblock %}

{% block content %}

<h1>Delete Auto</h1>

<p>Are you sure you want to delete the auto: {{ department.name }}?</p>

<form action="" method="POST">
  {% csrf_token %}
    <input type="submit" value="Submit">
    <input type="submit" onclick="window.location='{% url 'employee:start' %}' ; return false;" value="Cancel">
</form>


{% endblock %}

employee_management/employee/templates/CRUD_template/employee/department_form.html
{% extends 'base.html' %}
{% load static %}
{% block title %}główna{% endblock %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
    <input type="submit" onclick="window.location='{% url 'employee:start' %}' ; return false;" value="Cancel">
  </form>
{% endblock %}

employee_management/employee/templates/CRUD_template/employee/department_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}główna{% endblock %}

{% block content %}
   <h1>Department List</h1>
  {% if departments %}
  <ul>
    {% for dept in departments %}
      <li>
          {{ dept.name }}
          (<a href="{% url 'employee:dept_update' dept.id %}">Update</a> |
          <a href="{% url 'employee:dept_delete' dept.id %}">Delete</a>) <br/>
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no autos in the library.</p>
  {% endif %}
  <p>
    {% if department_count > 0 %}
      <a href="{% url 'employee:dept_create' %}">Add an auto</a>
    {% else %}
      Please add a make before you add an auto.
    {% endif %}
  </p>
  <p>
  <p>
    <a href="{% url 'employee:start' %}">Back to main side</a>
  </p>
    <a href="{% url 'employee:dept_create' %}">Add a make</a>
  </p>
{% endblock %}

employee_management/employee/templates/CRUD_template/employee_confirm_delete.html
{% extends 'base.html'%}
{% load static %}
{% block title %}główna{% endblock %}

{% block content %}

<p>Are you sure you want to delete the make: {{ employee.usercode }} - {{ employee.first_name }} {{ employee.last_name }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
  <input type="submit" onclick="window.location='{% url 'employee:start' %}' ; return false;" value="Cancel">
</form>

{% endblock %}

employee_management/employee/templates/CRUD_template/employee_list.html
{% extends 'base.html'%}
{% load static %}
{% block title %}główna{% endblock %}

{% block content %}
  <h1>Make List</h1>
  {% if employee %}
  <ul>
    {% for worker in employee %}
      <li>
          {{ worker.usercode }} - {{ worker.first_name }} {{ worker.last_name }}
         (<a href="{% url 'employee:update_employee' worker.id %}">Update</a> |
          <a href="{% url 'employee:delete_employee' worker.id %}">Delete</a>)
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no makes in the library.</p>
  {% endif %}
  <p><a href="#">Add a make</a></p>
  <p>
    <a href="{% url 'employee:start' %}">Back to main side</a>
  </p>
{% endblock %}

employee_management/employee/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="pl">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale = 1.0, maximum-scale=1.0, user-scalable=no" />
<title>{% block title %} {% endblock %}</title>
{% block styles %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link href="{% static 'employee.css' %}" rel="stylesheet">
{% endblock %}

</head>
<body>

{% block content %}
    material z base
{% endblock %}

</body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</html>

employee_management/employee/templates/login.html
{% extends 'base.html'%}
{% load crispy_forms_filters %}
{% load static %}
{% block title %}Login{% endblock %}

{% block content %}
    {% load crispy_forms_tags %}
<div class="container py-5">
  <h1>Login</h1>
  <form method="POST">
    {% csrf_token %}
    {{ login_form|crispy }}
    <button class="btn btn-primary" type="submit">Login</button>

  </form>
  <p class="text-center">Don't have an account? <a href="/register">Create an account</a>.</p>
</div>
{% endblock %}

employee_management/employee/templates/main_side.html
{% extends 'base.html'%}
{% load static %}
{% block title %}główna{% endblock %}

{% block content %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-link " aria-current="page" href="{% url 'employee:register' %}">Register</a>
        <a class="nav-link" href="{% url 'employee:login_request' %}">Login</a>
        <a class="nav-link" href="{% url 'employee:logout_request' %}">Logout</a>

      </div>
    </div>
  </div>
</nav>
<div class="display-5 text-start ml-2 mt-2">
{% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
    <a href="{% url 'employee:add_employee' %}">Dodaj Pracownika</a><br>

 <a href="{% url 'employee:list_employee' %}">Lista Pracowników</a><br>
 <a href="{% url 'employee:dept_create' %}">Dodaj dział</a><br>
 <a href="{% url 'employee:dept_list' %}">Lista działów</a><br>

<p>dodaj operacje</p>

<p></p>
<p></p>
</div>
{% endblock %}

employee_management/employee/templates/register.html
{% extends 'base.html'%}
{% load crispy_forms_filters %}
{% load static %}
{% block title %}główna{% endblock %}

{% block content %}
{% load crispy_forms_tags %}

<div class="container py-5">
	<h1>Register</h1>
	<form method="POST">
		{% csrf_token %}
		{{ register_form|crispy }}
		<button class="btn btn-primary" type="submit">Register</button>
	</form>
	<p class="text-center">If you already have an account, <a href="/login">login</a> instead.</p>
</div>

{% endblock %}